data: 
  path_to_test_file: "/data/ravinascos/Lund_Plane_2024_graphs/New_Samples/TEST_05qcd_1z/*.root"  
  path_to_outdir: "/data/ravinascos/LundNet/R_22_Top/TEST_NewData_05qcd_1z/"
  weights_file: ""
  signal_jet_truth_label: 1   # 1 for top and 2 for W
  scale_factor: 1
  kT_cut: 2.8 ## indeed this is a cut in ln(kT)

test:
  path_to_combined_ckpt: "/home/ravinascos/LundNet/Jad_git/lundtoptagger/Models/LundNet_R22_ExtraNode_ln_kT_Cut_2.8_LRJ_NewData_Primarye020_0.17321.pt"
  output_name: "LundNet_R22_ExtraNode_ln_kT_Cut_2.8_LRJ_NewDatae020"
  choose_model: "LundNet"
  learning_rate: 0.001
  batch_size: 2000
