data:
  #path_to_trainfiles: "/data/ravinascos/Lund_Plane_2024_graphs/TRAIN_DUMMY_01QCD_05Z/*.root" #TRAIN_DUMMY_fewEvents # TRAIN_DUMMY_01QCD_05Z
  # path_to_trainfiles: '/data/ravinascos/Lund_Plane_2024_graphs/TRAIN_DUMMY_02QCD_1Z/*.root'
  # path_to_trainfiles: '/eos/home-t/tmlinare/Lund/jetetmiss/JETMDataMC/jpierre/run/submitDir-2024-12-17-1734-0b3d flat mass W local (first success)/data-ANALYSIS/*.root'
  path_to_trainfiles: '/eos/home-t/tmlinare/Lund/jetetmiss/JETMDataMC/jpierre/run/submitDir-2025-01-07-0643-4c75 files 1-2/data-ANALYSIS/mc20_13TeV.802017.Py8EG_A14NNPDF23LO_WprimeWZ_flatpT_wideWmass.deriv.DAOD_JETM2.e8482_s3797_r13145_p5548_files_1-2.root'
  #path_to_save: "/home/ravinascos/LundNet/Jad_git/lundtoptagger/Models/"
  # path_to_save: "/data/ravinascos/LundNet/2024_graphs/"
  path_to_save: "/eos/home-t/tmlinare/Lund/Lund_tagging/lundtoptagger_data/"
  signal_jet_truth_label: 2   # 1 for top and 2 for W
  model_name: "TEST_"
  #"LundNet_R22_TRAIN_01QCD_05Z_Primary_FIX_ExtraNode_kt_.0"
# LundNet_R22_TRAIN_01QCD_05Z_Primary_ExtraNode_NormalSignalWeights

architecture:
  test_size: 0.2
  kT_cut: 0 ## indeed this is a cut in ln(kT)
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet
