data:
  path_to_trainfiles: "/data/ravinascos/Lund_Plane_2024_graphs/New_Samples/Pythia_TRAIN_05QCD_25Z_25W/*.root"
  path_to_save: "/data/ravinascos/LundNet/2024_graphs/"
  model_name: "LundNet_R22_ExtraNode_ln_kT_Cut_-0.5_LRJ_NewData_Primary"

architecture:
  batch_size: 1200
  test_size: 0.2
  n_epochs: 30
  learning_rate: 0.0005
  kT_cut: -0.5 ## indeed this is a cut in ln(kT)
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet
  save_every_epoch: True

retrain:
  flag: False
  path_to_ckpt: "/sps/atlas/k/khandoga/TrainGNN/Models/LundNet_ufob_e012_0.12481.pt"
