data:
  # path_to_trainfiles: "/data/ravinascos/LundNet/2024_graphs/graphs_NewDataset_LundNet_R22_No_ln_kT_Cut_LRJ_NewData_Primary"
  path_to_trainfiles: "/data/ravinascos/LundNet/2024_graphs/graphs_NewDataset_LundNet_R22_ExtraNode_ln_kT_Cut_{ln_kT_cut}_LRJ_NewData_Primary"  # can also be a list of paths
  path_to_save: "/home/ravinascos/LundNet/Jad_git/lundtoptagger/Models/"
  # model_name: "LundNet_R22_ExtraNode_No_ln_kT_Cut_LRJ_NewData_Primary"
  model_name: "LundNet_R22_ExtraNode_ln_kT_Cut_{ln_kT_cut}_LRJ_NewData_Primary"
  ln_kT_cut: null # null, -0.5, 0.0, 0.5, 1.0, 2.0, 2.8
  # if {ln_kT_cut} is present in path_to_trainfiles or model_name, it will be replaced by the value of ln_kT_cut (by None if ln_kT_cut is null)
  # the value from this config file and can be overriden by the command-line argument --ln_kT_cut

architecture:
  batch_size: 4500 #2600
  test_size: 0.1
  n_epochs: 35
  learning_rate: 0.0004 # 0.0005 for ln_kT_cut=2.8?
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet
  save_every_epoch: True

retrain:
  flag: False
  path_to_ckpt: "/sps/atlas/k/khandoga/TrainGNN/Models/LundNet_ufob_e012_0.12481.pt"
