data:
  #path_to_trainfiles: "./data/graphs_NewDataset_LundNet_R22_TEST_005QCD_01ZPrimary_" #graphs_NewDataset_LundNet_R22_TESTPrimary_
  path_to_trainfiles: "/data/ravinascos/LundNet/2024_graphs/graphs_NewDataset_LundNet_R22_TEST_005QCD_01ZPrimary_"
  path_to_save: "/home/ravinascos/LundNet/Jad_git/lundtoptagger/Models/"
  model_name: "LundNet_R22_TEST2Primary_"

architecture:
  batch_size: 1600
  test_size: 0.2
  n_epochs: 40
  learning_rate: 0.0005
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet
  save_every_epoch: True

retrain:
  flag: False
  path_to_ckpt: "/sps/atlas/k/khandoga/TrainGNN/Models/LundNet_ufob_e012_0.12481.pt"
