data: 
  path_to_test_file: "/data/ravinascos/Lund_Plane_2024_graphs/New_Samples/Other_MC/Herwig_d/*.root"  
  path_to_outdir: "/data/ravinascos/LundNet/R_22_Top/Other_MC/"
  weights_file: ""
  scale_factor: 1
  kT_cut: -0.5 ## indeed this is a cut in ln(kT)

test:
  path_to_combined_ckpt: "/home/ravinascos/LundNet/Jad_git/lundtoptagger/Models/LundNet_R22_ExtraNode_ln_kT_Cut_-0.5_LRJ_NewData_Primarye020_0.10169.pt"
  output_name: "Herwigd_KtCut_-0.5_"
  choose_model: "LundNet"
  learning_rate: 0.001
  batch_size: 2000
