data: 
  path_to_test_file: "/data/ravinascos/Lund_Plane_2024_graphs/New_Samples/Other_MC/Sherpa_Cluster/*.root"  
  path_to_outdir: "/data/ravinascos/LundNet/R_22_Top/Other_MC/"
  weights_file: ""
  scale_factor: 1
  kT_cut: -500 ## indeed this is a cut in ln(kT)

test:
  path_to_combined_ckpt: "/home/ravinascos/LundNet/Jad_git/lundtoptagger/Models/LundNet_R22_ExtraNode_No_ln_kT_Cut_LRJ_NewData_Primarye020_0.09045.pt"
  output_name: "Sherpa_Cluster_KtCut_None_"
  choose_model: "LundNet"
  learning_rate: 0.001
  batch_size: 2000
